[package]
name = 'counter'
version = '1.0.0'

[addresses]
counter = "0x1"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'
